build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
  artifacts:
    paths:
    - build

test-listDirs:
  stage: test
  script:
    - echo $PWD
    - g++  tests/listDirectories.cpp -lstdc++fs -std=c++17 src/getFiles.cpp  -o listDirectories.bin 
    - ./listDirectories.bin

test-listDirsScript:
  stage: test
  script:
    - echo $PWD
    - ./tests/scripts/listDirectories.sh
    - ./listDirectories.bin


test-fs:
  stage: test
  script:
    - echo $PWD
    - ./tests/scripts/fileSystemCheck.sh
    - ./fileSystemCheck.bin 

