build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
    - cd ..
    - ./tests/bin/bin.app
    - ./tests/bin/bin.app --threads=2 --cycles=2
  artifacts:
    paths:
    - build

test-listDirsScript:
  stage: test
  script:
    - echo $PWD
    - ./tests/scripts/listDirectories.sh
    - ./listDirectories.bin


test-fs:
  stage: test
  script:
    - echo $PWD
    - ./tests/scripts/fileSystemCheck.sh
    - ./fileSystemCheck.bin 

test-splitListByThread:
  stage: test
  script:
    - ./tests/scripts/splitListByThread.sh
    - ./splitListByThread.bin 

test-async-inputDir:
  stage: test
  script:
    - ./tests/scripts/checkForInputDir.sh
    - ./tests/bin/checkForInputDir.bin 

test-cliparse:
  stage: test
  script:
    - ./tests/scripts/cli_parser.sh
    - ./tests/bin/cli_parser.bin
    - ./tests/bin/cli_parser.bin --threads=2 --cycles=6


